Resolves #54: adds 'dot' match option
do-community/glob-tool pull request #61
Opened 2022-11-27 02:11 UTC by webketje

Manually integration-tested including loading from & saving to URL querystring

## Type of Change

- **Tool Source:** Vue (app.vue), i18n
## What issue does this relate to?
Resolves #54 

### What should this PR do?
Adds "matchOptions" object to Vue app with (for the time being) a single option: dot (mirroring minimatch's).
Loads the option from & saves it to the URL querystring (as `options=dot:true`)
Also sets up foundation for adding support for other minimatch options

### What are the acceptance criteria?
Please check the translation.

| before | after |
|----------| --------|
|![Imgur](https://i.imgur.com/dzJCpvR.png) | ![Imgur](https://i.imgur.com/l9gjpNe.png) | |

2022-11-28 12:37 UTC, MattIPv4 requested changes
Ty for doing this -- two minor thoughts

2022-11-28 12:37 UTC, MattIPv4 commented on src/glob-tool/templates/app.vue
>              }
```suggestion
            matchOptions: {
                handler() {
                    this.test()
                },
                deep: true,
            },
```
To future-proof this if other settings are added, can we use a deep watcher for the whole object?

2022-11-28 12:37 UTC, MattIPv4 commented on src/glob-tool/templates/app.vue
> +                    console.log(this.matchOptions)
```suggestion
```

2022-11-28 23:26 UTC, webketje commented on src/glob-tool/templates/app.vue
> +                    console.log(this.matchOptions)
Oops.. forgot this

2022-11-28 23:34 UTC, webketje commented
PS: before I commit fixes, any input regarding the translation?
Maybe it would be better to state "wildcards match path segments starting with a dot" (this is for all of `?`, `*`, and `**`)

2022-11-28 23:42 UTC, MattIPv4 commented
`Allow wildcards to match dotfiles?` maybe?

2022-11-28 23:59 UTC, webketje commented
> `Allow wildcards to match dotfiles?` maybe?

That is less complete though, as you can see in the "AFTER" screenshot it applies to any path segments with dots (eg also `.git/.nested/.env`)

2022-11-29 00:11 UTC, webketje commented
Ok I changed it to something I think is both clearer and more complete and adressed the issues you highlighted.
Feel free to change the translation later if you find a better match :smile:

2022-11-29 00:58 UTC, MattIPv4 commented
@webketje what you have works for me -- would you mind rebasing against master again, I just merged a PR with the testing workflow marked as required here?

2022-11-29 19:37 UTC, webketje commented
Bump - done

2022-11-29 19:45 UTC, MattIPv4 approved these changes
LGTM, ty!

2022-11-29 19:46 UTC, merged